name: monster_tap_game
description: A fun tap game for kids aged 4-8
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flame: ^1.10.0
  flame_audio: ^2.11.14
  shared_preferences: ^2.5.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/backgrounds/
    - assets/images/items/
    - assets/images/characters/world1/monster_main/
    - assets/images/characters/world1/monster_main/accessories/
    - assets/images/characters/world2/monster_main/
    - assets/images/characters/world2/monster_main/accessories/
    - assets/sounds/
